# Generated by Django 5.2.14 on 2026-05-12 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fetcher', '0003_extractionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Botswana Mining Alerts'.", max_length=255)),
                ('keywords', models.TextField(help_text='Comma-separated keywords. An article matches if any keyword appears (case-insensitive) in the title or body.')),
                ('source_domain', models.CharField(blank=True, help_text="Restrict to this domain only, e.g. 'miningweekly.com'. Leave blank for all.", max_length=255)),
                ('language', models.CharField(blank=True, help_text="ISO 639-1 code, e.g. 'en'. Leave blank for all languages.", max_length=10)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Restrict to articles with this sentiment. Leave blank for all.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address to notify on match.', max_length=254)),
                ('webhook_url', models.URLField(blank=True, help_text='HTTP endpoint to POST a JSON payload to on match.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_keywords', models.JSONField(default=list, help_text='Which keywords from the alert were found in this article.')),
                ('notified', models.BooleanField(db_index=True, default=False, help_text='True once at least one notification was sent successfully.')),
                ('notified_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful notification dispatch.', null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='alerts.alert')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_matches', to='fetcher.parsedarticle')),
            ],
            options={
                'verbose_name': 'Alert Match',
                'verbose_name_plural': 'Alert Matches',
                'ordering': ['-created_at'],
                'unique_together': {('alert', 'article')},
            },
        ),
    ]
