# Generated by Django 4.2.13 on 2026-04-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status_code', models.PositiveSmallIntegerField(help_text='HTTP response status code, e.g. 200, 404, 500.')),
                ('content_type', models.CharField(blank=True, help_text='Value of the Content-Type response header.', max_length=255)),
                ('encoding', models.CharField(blank=True, help_text='Character encoding detected or declared by the server.', max_length=50)),
                ('raw_html', models.TextField(help_text='Full HTML body of the response.')),
                ('fetch_duration_ms', models.PositiveIntegerField(default=0, help_text='How long the HTTP request took, in milliseconds.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this page was fetched.')),
                ('discovered_url', models.OneToOneField(help_text='The URL this page was fetched from.', on_delete=django.db.models.deletion.CASCADE, related_name='fetched_page', to='discovery.discoveredurl')),
            ],
            options={
                'verbose_name': 'Fetched Page',
                'verbose_name_plural': 'Fetched Pages',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Article headline.', max_length=512)),
                ('body_text', models.TextField(blank=True, help_text='Full plain-text body of the article, stripped of HTML.')),
                ('summary', models.TextField(blank=True, help_text='Auto-generated summary (from NLP or meta description).')),
                ('author', models.CharField(blank=True, help_text='Author name(s), comma-separated if multiple.', max_length=255)),
                ('published_at', models.DateTimeField(blank=True, help_text='Article publication date extracted from the page.', null=True)),
                ('source_domain', models.CharField(blank=True, db_index=True, help_text="Hostname of the source URL, e.g. 'www.miningweekly.com'.", max_length=255)),
                ('language', models.CharField(blank=True, help_text="ISO 639-1 language code, e.g. 'en', 'fr'.", max_length=10)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Keywords or tags extracted from the page metadata.')),
                ('signals', models.JSONField(blank=True, default=dict, help_text='NLP-derived signals: keywords, named entities, sentiment, etc.')),
                ('fetched_page', models.OneToOneField(help_text='The raw page this article was parsed from.', on_delete=django.db.models.deletion.CASCADE, related_name='parsed_article', to='fetcher.fetchedpage')),
            ],
            options={
                'verbose_name': 'Parsed Article',
                'verbose_name_plural': 'Parsed Articles',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['source_domain'], name='fetcher_par_source__e7588d_idx'), models.Index(fields=['published_at'], name='fetcher_par_publish_eaf1c8_idx'), models.Index(fields=['language'], name='fetcher_par_languag_c1f6b2_idx')],
            },
        ),
    ]
