# Generated by Django 5.2.14 on 2026-05-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_extractionrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedarticle',
            name='country',
            field=models.CharField(blank=True, db_index=True, help_text='Publication country of the article (never empty after parse).', max_length=100),
        ),
    ]
