# Generated by Django 4.2.13 on 2026-04-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Mining Weekly RSS'.", max_length=255)),
                ('url', models.URLField(help_text='The feed URL, sitemap URL, or page to crawl.', unique=True)),
                ('source_type', models.CharField(choices=[('rss', 'RSS / Atom Feed'), ('sitemap', 'XML Sitemap'), ('seed_url', 'Seed URL (link extraction)'), ('search_api', 'Search API (Bing / Google)'), ('manual', 'Manually Added')], default='rss', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive seeds are skipped by the scheduler.')),
                ('crawl_interval', models.PositiveIntegerField(default=60, help_text='How often to re-crawl this source, in minutes. 0 = manual only.')),
                ('last_crawled_at', models.DateTimeField(blank=True, help_text='Set automatically each time discovery runs.', null=True)),
                ('keyword_filter', models.TextField(blank=True, help_text='Comma-separated keywords. When set, only URLs/articles whose title, snippet, or URL contain at least one keyword are stored. Leave empty to capture everything.')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Source-type-specific config as JSON. Examples: {"max_depth": 2} for sitemaps, {"provider": "bing", "query": "gold mining"} for search API.')),
            ],
            options={
                'verbose_name': 'Seed Source',
                'verbose_name_plural': 'Seed Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='The discovered article or page URL.', max_length=2048)),
                ('url_hash', models.CharField(db_index=True, editable=False, help_text='SHA-256 of the URL. Set automatically. Used for deduplication.', max_length=64, unique=True)),
                ('title', models.CharField(blank=True, help_text='Title from the RSS entry or link anchor text.', max_length=512)),
                ('snippet', models.TextField(blank=True, help_text='Short summary from the feed or search result.')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date if available from the discovery source.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('fetched', 'Fetched'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Populated when status=failed.')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_urls', to='discovery.seedsource')),
            ],
            options={
                'verbose_name': 'Discovered URL',
                'verbose_name_plural': 'Discovered URLs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('retry', 'Retry')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('fetched', 'Fetched'), ('parsed', 'Parsed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, help_text='The Celery task ID, for tracking in Flower.', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, help_text='HTTP response code from the fetch attempt.', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('discovered_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_jobs', to='discovery.discoveredurl')),
            ],
            options={
                'verbose_name': 'Crawl Job',
                'verbose_name_plural': 'Crawl Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['status'], name='discovery_d_status_a7ab52_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['seed', 'status'], name='discovery_d_seed_id_eef479_idx'),
        ),
        migrations.AddIndex(
            model_name='discoveredurl',
            index=models.Index(fields=['published_at'], name='discovery_d_publish_d7d68b_idx'),
        ),
    ]
